import Head from "next/head";
import Genres from "../src/components/Genres";
import Movies from "../src/components/Movies";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl text-center">Welcome to TMDB</h1>
        <Genres />
        <Movies />
      </main>
    </div>
  );
}
